### ISSUE TITLE
Cannot setup on 2021.12 ( Unable to import component: cannot import name 'HTTP_OK' ...)

### ISSUE THREAD

**Issue by ildar170975** [Limych/ha-gismeteo#90]
**Environment**

- Home Assistant Core release with the issue: 2021.12.0
- This custom component release with the issue: 2.3.3
- Last working this custom component release (if known): 2.3.3
- Operating environment (Home Assistant/Supervisor/Docker/venv): HA in Docker

**Describe the bug**

The integration cannot setup on HA startup.
There is an error in the log:
```
Setup failed for gismeteo: Unable to import component: cannot import name 'HTTP_OK' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

**Configuration.yaml**
The integration is setup via UI.

**Steps to Reproduce**

Upgrade HA to 2021.12

**Expected behavior**

The integration is loaded on HA startup.

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by IgorAga** [comment]
I've got the same problem after upgrading to 2021.12 last night. Configuration and error messages are exactly the same.

**Comment by AlexeyHimki** [comment]
same

**Comment by Sacr87** [comment]
Same issue

**Comment by DIYZi** [comment]
I've got the same problem after upgrading to 2021.12.0

**Comment by yuri-vashchenko** [comment]
the same here

**Comment by huligan575** [comment]
problem after upgrading to 2021.12.0

**Comment by strelok15** [comment]
Quick temporary fix in api.py, similar as there
    [Use http.HTTPStatus instead of const.HTTP_*](https://github.com/scop/ha-narodmon/commit/5e4558edb56652355429ff6790d8f7bdfe5bcea7)

**Comment by urikst** [comment]
Workaround: api.py file, line 50,
it was
    ATTR_NAME,
    HTTP_OK,
    STATE_UNKNOWN,
)
became:
    ATTR_NAME,
    STATE_UNKNOWN,
)
HTTP_OK = 200

**Comment by ildar170975** [comment]
> Quick temporary fix in api.py, similar as there [Use http.HTTPStatus instead of const.HTTP_*](https://github.com/scop/ha-narodmon/commit/5e4558edb56652355429ff6790d8f7bdfe5bcea7)

Can anyone help me to apply the fix?
I am using HA in Docker.

**Comment by baronrustamov** [comment]
where is api.py file?

**Comment by IgorAga** [comment]
> where is api.py file?

[HA root (location of configuration.yaml)]/custom_components/gismeteo/api.py

**Comment by baronrustamov** [comment]
it works, thank you

**Comment by sivanikov** [comment]
same error

**Comment by ildar170975** [comment]
This fix helped me - https://github.com/Limych/ha-gismeteo/issues/90#issuecomment-991896750

**Comment by judgen2005** [comment]
> It works. Thanks.

**Comment by 232max232** [comment]
Error:
File "/config/custom_components/gismeteo/api.py", line 53
    HTTP_OK = 200

**Comment by dezzzm** [comment]
This fixes don't help me. 
error: `Error occurred loading configuration flow for integration gismeteo: cannot import name 'HTTP_OK' from 'homeassistant.const'`
Home Assistant 2021.12.3

**Comment by Limych** [comment]
Fixed in #87
